# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664330b980e63b3feabfcf3a10a203cc7788cc22644ac93a7a55c5816931fcb28e98a438fd06ae7250903eb2ad2b05c6c0ceafc09521758810bcf6cc9231d819

test:
  secret_key_base: 5c8bffe2a6b7d35828dfef3e6ee46c678424df01080b6deb745aa8aa4e5069344b292a5e2fb1f592c4f7fa8fa071a193ac2e4bd6575628a09e266db7e95524ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
